const govukPrototypeKit = require('govuk-prototype-kit')
const controller = require('./controller')

const router = govukPrototypeKit.requests.setupRouter('/v6/find-guidance')

router.get('/', controller.get)
router.get('/new', controller.getNew)
router.post('/new', controller.postNew)
router.get('/remove-confirm', controller.getRemoveConfirm)
router.post('/remove', controller.postRemove)
router.get('/document/:id', controller.getDocument)
router.get('/organic-search', controller.getOrganicSearch)
router.post('/save-to-search', controller.postSaveToSearch)
router.get('/ai-search', controller.getAiSearch)
router.get('/ai-search-loading', controller.getAiSearchLoading)
router.post('/ai-search-loading', controller.postAiSearchLoading)
router.get('/ai-search-results', controller.getAiSearchResults)
router.get('/ai-search-results/:id', controller.getAiSearchResults)
router.get('/ai-search-results/:id/:step', controller.getAiSearchResults)
